# ENVS FOR MAIN CONTAINER
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HELM_PLUGINS
    value: /custom-tools/helm-plugins/

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HELM_SECRETS_CURL_PATH
    value: /custom-tools/curl

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HELM_SECRETS_SOPS_PATH
    value: /custom-tools/sops

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HELM_SECRETS_VALS_PATH
    value: /custom-tools/vals

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HELM_SECRETS_KUBECTL_PATH
    value: /custom-tools/kubectl

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HELM_SECRETS_BACKEND
    value: sops

# https://github.com/jkroepke/helm-secrets/wiki/Security-in-shared-environments
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
    value: "false"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
    value: "true"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
    value: "false"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HELM_SECRETS_WRAPPER_ENABLED
    value: "true"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HELM_SECRETS_HELM_PATH
    value: /usr/local/bin/helm

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HELM_SECRETS_LOAD_GPG_KEYS
    # Multiple keys can be separated by space
    value: /helm-secrets-private-keys/key.asc

# VOLUMES
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: custom-tools
    emptyDir: {}

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: helm-secrets-private-keys
    secret:
      secretName: helm-secrets-private-keys

# VOLUME MOUNTS FOR MAIN CONTAINER
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /custom-tools
    name: custom-tools

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /usr/local/sbin/helm
    subPath: helm
    name: custom-tools

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /helm-secrets-private-keys/
    name: helm-secrets-private-keys

# INIT CONTAINER
- op: add
  path: /spec/template/spec/initContainers/-
  value:
    name: download-tools
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    command: [sh, -ec]
    env:
      - name: HELM_SECRETS_VERSION
        value: "4.4.2"
      - name: KUBECTL_VERSION
        value: "1.26.1"
      - name: VALS_VERSION
        value: "0.24.0"
      - name: SOPS_VERSION
        value: "3.7.3"
    args:
      - |
        mkdir -p /custom-tools/helm-plugins
        wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-;

        wget -qO /custom-tools/curl https://github.com/moparisthebest/static-curl/releases/latest/download/curl-amd64
        wget -qO /custom-tools/sops https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux
        wget -qO /custom-tools/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl

        wget -qO- https://github.com/helmfile/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_amd64.tar.gz | tar -xzf- -C /custom-tools/ vals;

        cp /custom-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /custom-tools/helm

        chmod +x /custom-tools/*
    volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
