apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./argo-cd
- ./argocd-image-updater

patches:
  - target:
      kind: Deployment
      name: argocd-repo-server
    path: ./helm-secrets/argocd-repo-server.yaml

patchesStrategicMerge:
  - ./helm-secrets/argocd-cm.yaml
